<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Roboto:300,400,500,700">
<link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/icon?family=Material+Icons">
<link rel="stylesheet" type="text/css" href="<?= $this->helper->getModuleResourcePath('Admin','css/reset.min.css');  ?>" />
<link rel="stylesheet" type="text/css" href="<?= $this->helper->getModuleResourcePath('Admin','css/bootstrap.min.css');  ?>" />
<link rel="stylesheet" type="text/css" href="<?= $this->helper->getModuleResourcePath('Admin','css/bootstrap-material-design.min.css');  ?>" />
<link rel="stylesheet" type="text/css" href="<?= $this->helper->getModuleResourcePath('Admin','css/ripples.min.css');  ?>" />	
<link rel="stylesheet" type="text/css" href="<?= $this->helper->getModuleResourcePath('Admin','plugins/jScrollPane/style/jquery.jscrollpane.css');  ?>" />
<link rel="stylesheet" type="text/css" href="<?= $this->helper->getModuleResourcePath('Admin','plugins/DataTables-1.10.12/media/css/jquery.dataTables.min.css');  ?>" />
<link rel="stylesheet" type="text/css" href="<?= $this->helper->getModuleResourcePath('Admin','plugins/bootstrap-material-datetimepicker-gh-pages/css/bootstrap-material-datetimepicker.css');  ?>" />
<link rel="stylesheet" type="text/css" href="<?= $this->helper->getModuleResourcePath('Admin','css/admin_styles.css');  ?>" />

<script type="text/javascript" src="<?= $this->helper->getModuleResourcePath('Admin','plugins/media-tricks/respond.min.js');  ?>" data-role="work-around"></script>
<script type="text/javascript" src="<?= $this->helper->getModuleResourcePath('Admin','js/jquery-1.9.1.js');  ?>" data-role="work-around"></script>
<script type="text/javascript" src="<?= $this->helper->getModuleResourcePath('Admin','plugins/jquery.mobile.custom/jquery.mobile.custom.min.js');  ?>" data-role="plugin"></script>
<script type="text/javascript" src="<?= $this->helper->getModuleResourcePath('Admin','plugins/jsform.js');  ?>" data-role="plugin"></script>
<script type="text/javascript" src="<?= $this->helper->getModuleResourcePath('Admin','plugins/jScrollPane/script/jquery.mousewheel.js');  ?>" data-role="plugin"></script>
<script type="text/javascript" src="<?= $this->helper->getModuleResourcePath('Admin','plugins/DataTables-1.10.12/media/js/jquery.dataTables.min.js');  ?>" data-role="plugin"></script>
<script type="text/javascript" src="<?= $this->helper->getModuleResourcePath('Admin','plugins/moment.min.js');  ?>" data-role="plugin"></script>
<script type="text/javascript" src="<?= $this->helper->getModuleResourcePath('Admin','plugins/bootstrap-material-datetimepicker-gh-pages/js/bootstrap-material-datetimepicker.js');  ?>" data-role="plugin"></script>
<script type="text/javascript" src="<?= $this->helper->getModuleResourcePath('Admin','js/bootstrap.min.js');  ?>" data-role="plugin"></script>
<script type="text/javascript" src="<?= $this->helper->getModuleResourcePath('Admin','js/material.min.js');  ?>" data-role="plugin"></script>
<script type="text/javascript" src="<?= $this->helper->getModuleResourcePath('Admin','js/ripples.min.js');  ?>" data-role="plugin"></script>
<script class="jsref:client" data-id="_bu" data-setup="dynamic:configured" data-type="varchar" data-content="<?= $this->helper->getBaseUrl(); ?>">
	$(document).ready(function(){
		$.material.init()
	});
</script>
<noscript>	
	<style>
		.noscript{
			position: fixed;
		    top: 0;
		    text-align: center;
		    left: 0;
		    right: 0;
		    bottom: 0;
		    background: #2d2d2d;
		    color: #fff;
		    padding-top: 10%;
		}
	</style>
	<div class="noscript">
		<h3>Oops!</h3>
		This website utilizes JavaScript for enhanced functionality and user experience.<br/>Your browser may not have JavaScript or it may be disabled. Please enable javascript to continue using this web application.
	</div>
</noscript>